version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kompetisiku
    ports:
      - $MYSQLDB_LOCAL_PORT:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./login-signup
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:5000
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=kompetisiku
      - DB_PORT=3306
    stdin_open: true
    tty: true

volumes: 
  db: